services:
    nginx-web:
      image: nginx:latest
      container_name: nginx-web
      ports:
        - 8000:80
        - .:/usr/share/nginx/html
      networks:
        - backend_network
networks:
  backend_network
